version: "3.9"

services:
  graphql:
    build:
      context: docker/graphql
      args:
        - uid=${CONTAINER_USER_UID}
    working_dir: /app
    environment:
      - CARGO_TARGET_DIR=/cargo_target
    command: cargo watch -x 'run'
    volumes:
      - ./:/app
      - cargo_target_vol:/cargo_target

volumes:
  cargo_target_vol:
    driver: local
