version: "3.9"

services:
  graphql:
    build:
      context: docker/graphql
      args:
        - uid=${CONTAINER_USER_UID}
    working_dir: /app
    environment:
      - CARGO_TARGET_DIR=/cargo_target
    command: cargo watch -x 'run'
    volumes:
      - ./:/app
      - cargo_target_vol:/cargo_target
  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=playground_dev
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql_vol:/var/lib/mysql
# 本番ビルドを試したい場合は、以下のコメントを docker-compose.override.yml にコピーして実行
#  graphql_prod:
#    build:
#      context: .
#      dockerfile: docker/graphql_prod/Dockerfile
#    environment:
#      - DATABASE_URL=${DATABASE_URL}
#    ports:
#      - "8089:8080"

volumes:
  cargo_target_vol:
    driver: local
  mysql_vol:
    driver: local

